
# correct rotations / component placement for JLCPCB

import csv, sys, decimal

posfile = open(sys.argv[1], 'r')
records = csv.DictReader(posfile)

in_cols = [ 'Ref','Val','Package','PosX','PosY','Rot','Side' ]

unknown = """color("red")cylinder(h=5,r=2);"""

package_map = {

	'R_0402_1005Metric':'r0402()',
	'R_0603_1608Metric':'r0603()',

	'C_0402_1005Metric':'c0402()',
	'C_0603_1608Metric':'c0603()',

	'LED_0603_1608Metric_Pad1':'l0603()',
	'LED_0603_1608Metric':'l0603()',

	'SW_Push_1P1T_NO_CK_KMR2': 'kmr2()',

	'SOT-23-5' : 'sot235()',

	'QFN-28_4x4mm_P0.5mm': 'ufqfpn28()',

	'SOT-666': 'sot666()',

	'USB_C_Receptacle_HRO_TYPE-C-31-M-12': 'usb_c_type_c31_m12()',
}

layer_action = {'top':'','bottom':'rotate([180,0,0])\n'}

print ("""

/*
 * this code is auto-generated by posfile_to_scad.py
 */

use <../../lib/usb.scad>;
use <../../lib/parts.scad>;

""")

def module(name,statements):
	print(f'module {name}()\n{{')
	print('\n'.join(statements))
	print(f'\n}}\n\n')

def process(row):

	x, y = decimal.Decimal(row['PosX']), decimal.Decimal(row['PosY']);
	rot = decimal.Decimal(row['Rot'])
	package = package_map.get(row['Package'], unknown)
	flip = layer_action[row['Side']]

	return f'translate([{x},{y},{0}])\n{flip}rotate([0,0,{rot}])\n{package};\n'


components_top = []
components_bottom = []

for row in records:
	if row['Side'] == 'top':
		components_top.append(process(row))
	else:
		components_bottom.append(process(row))

module("components_top", components_top)
module("components_bottom", components_bottom)

